=== mohamed7-dev/Gweb/features/apps-manager/lib/app.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Settings App Schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "slug": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "addToDock": {
      "type": "boolean"
    },
    "bin": {
      "type": "string"
    },
    "icon": {
      "type": "object",
      "properties": {
        "24@2x": { "type": "string" },
        "48@2x": { "type": "string" },
        "256@2x": { "type": "string" }
      },
      "required": ["24@2x", "48@2x", "256@2x"],
      "additionalProperties": false
    },
    "sidebar-view": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9-_]+$": {
          "type": "object",
          "properties": {
            "sidebarButton": { "type": "string" },
            "subTitle": { "type": "string" },
            "icon": { "type": "string" }
          },
          "required": ["sidebarButton", "subTitle", "icon"],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "required": ["id", "title", "slug", "version", "bin", "icon"],
  "additionalProperties": false
}

=== mohamed7-dev/Gweb/features/settings-app/__app__.json
{
  "$schema": "../apps-manager/lib/app.schema.json",
  "id": "gweb.app.settings",
  "title": "Settings",
  "slug": "settings",
  "version": "1.0.0",
  "addToDock": true,
  "bin": "@/features/settings-app/component/settings-app.tsx",
  "icon": {
    "24@2x": "/apps/24x24@2x/settings-app.png",
    "256@2x": "/apps/256x256@2x/settings-app.png",
    "48@2x": "/apps/48x48@2x/settings-app.png"
  },
  "sidebar-view": {
    "appearance": {
      "sidebarButton": "Appearance",
      "subTitle": "Appearance",
      "icon": "/scalable/apps/settings/settings-appearance-symbolic.svg"
    }
  }
}
